### PR TITLE
feat: VM

### PR DESCRIPTION
**Pull request by onlymateo**

### CODE REVIEW

**Comment by MrLego8-9** [comment]
fuck it

**Review by MrLego8-9 — APPROVED** [review]
NOT COMPLETE AND UNTESTED

FUCK IT !
YOLO!

**Review by PasVegan — APPROVED** [review]
noice, absolutely finished VM, thanks guys for your hard work

**Comment by MrLego8-9** [comment]
> noice, absolutely finished VM, thanks guys for your hard work

lul

**Pull request merged**
